version: '3.2'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 80:80/tcp
    volumes:
      - ./../../nginx:/etc/nginx/conf.d
      - ./public:/var/www/uw/src/public
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: ./../../php
    volumes:
      - ./public:/var/www/uw/src/public
      - ./vendor:/var/www/uw/vendor
    depends_on:
      - redis

  redis:
    image: redis:4.0.2
    restart: unless-stopped