version: '3.2'

services:
  app:
    image: nginx:1.13-alpine
    ports:
      - 8002:80/tcp
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public:/var/www/uw/src/public
    networks:
      - uw-internal-1
      - relations-1

  relations-php:
    image: uw-php
    volumes:
      - ./public:/var/www/uw/src/public
      - ./vendor:/var/www/uw/vendor
    ports:
      - 9000
    networks:
      - uw-internal-1
      - relations-1

  redis:
    image: redis:4.0.2
    networks:
      - relations-1

networks:
    uw-internal-1:
      external: true
    relations-1: